export default [
    {
        name: 'Microsoft Amina Online (Natural) - Arabic (Algeria)',
        lang: 'ar-DZ',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Ismael Online (Natural) - Arabic (Algeria)',
        lang: 'ar-DZ',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Laila Online (Natural) - Arabic (Bahrain)',
        lang: 'ar-BH',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Ali Online (Natural) - Arabic (Bahrain)',
        lang: 'ar-BH',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Salma Online (Natural) - Arabic (Egypt)',
        lang: 'ar-EG',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Shakir Online (Natural) - Arabic (Egypt)',
        lang: 'ar-EG',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Rana Online (Natural) - Arabic (Iraq)',
        lang: 'ar-IQ',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Bassel Online (Natural) - Arabic (Iraq)',
        lang: 'ar-IQ',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Sana Online (Natural) - Arabic (Jordan)',
        lang: 'ar-JO',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Taim Online (Natural) - Arabic (Jordan)',
        lang: 'ar-JO',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Noura Online (Natural) - Arabic (Kuwait)',
        lang: 'ar-KW',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Fahed Online (Natural) - Arabic (Kuwait)',
        lang: 'ar-KW',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Layla Online (Natural) - Arabic (Lebanon)',
        lang: 'ar-LB',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Rami Online (Natural) - Arabic (Lebanon)',
        lang: 'ar-LB',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Iman Online (Natural) - Arabic (Libya)',
        lang: 'ar-LY',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Omar Online (Natural) - Arabic (Libya)',
        lang: 'ar-LY',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Mouna Online (Natural) - Arabic (Morocco)',
        lang: 'ar-MA',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Jamal Online (Natural) - Arabic (Morocco)',
        lang: 'ar-MA',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Aysha Online (Natural) - Arabic (Oman)',
        lang: 'ar-OM',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Abdullah Online (Natural) - Arabic (Oman)',
        lang: 'ar-OM',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Amal Online (Natural) - Arabic (Qatar)',
        lang: 'ar-QA',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Moaz Online (Natural) - Arabic (Qatar)',
        lang: 'ar-QA',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Zariyah Online (Natural) - Arabic (Saudi Arabia)',
        lang: 'ar-SA',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Hamed Online (Natural) - Arabic (Saudi Arabia)',
        lang: 'ar-SA',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Amany Online (Natural) - Arabic (Syria)',
        lang: 'ar-SY',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Laith Online (Natural) - Arabic (Syria)',
        lang: 'ar-SY',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Reem Online (Natural) - Arabic (Tunisia)',
        lang: 'ar-TN',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Hedi Online (Natural) - Arabic (Tunisia)',
        lang: 'ar-TN',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Fatima Online (Natural) - Arabic (United Arab Emirates)',
        lang: 'ar-AE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Hamdan Online (Natural) - Arabic (United Arab Emirates)',
        lang: 'ar-AE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Maryam Online (Natural) - Arabic (Yemen)',
        lang: 'ar-YE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Saleh Online (Natural) - Arabic (Yemen)',
        lang: 'ar-YE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Majed',
        lang: 'ar-001',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Microsoft Hoda - Arabic (Arabic )',
        lang: 'ar-EG',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Naayf - Arabic (Saudi Arabia)',
        lang: 'ar-AS',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google ar-xa-x-arc-network',
        lang: 'ar',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google ar-xa-x-arz-network',
        lang: 'ar',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google ar-xa-x-ard-network',
        lang: 'ar',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google ar-xa-x-are-network',
        lang: 'ar',
        type: 'male',
        quality: 3,
    },
];
