import type { Voice } from '../Voice';

const data: Voice[] = [
    ['Microsoft Amina Online (Natural) - Arabic (Algeria)', 'ar-DZ', 'female', 4],
    ['Microsoft Ismael Online (Natural) - Arabic (Algeria)', 'ar-DZ', 'male', 4],
    ['Microsoft Laila Online (Natural) - Arabic (Bahrain)', 'ar-BH', 'female', 4],
    ['Microsoft Ali Online (Natural) - Arabic (Bahrain)', 'ar-BH', 'male', 4],
    ['Microsoft Salma Online (Natural) - Arabic (Egypt)', 'ar-EG', 'female', 4],
    ['Microsoft Shakir Online (Natural) - Arabic (Egypt)', 'ar-EG', 'male', 4],
    ['Microsoft Rana Online (Natural) - Arabic (Iraq)', 'ar-IQ', 'female', 4],
    ['Microsoft Bassel Online (Natural) - Arabic (Iraq)', 'ar-IQ', 'male', 4],
    ['Microsoft Sana Online (Natural) - Arabic (Jordan)', 'ar-JO', 'female', 4],
    ['Microsoft Taim Online (Natural) - Arabic (Jordan)', 'ar-JO', 'male', 4],
    ['Microsoft Noura Online (Natural) - Arabic (Kuwait)', 'ar-KW', 'female', 4],
    ['Microsoft Fahed Online (Natural) - Arabic (Kuwait)', 'ar-KW', 'male', 4],
    ['Microsoft Layla Online (Natural) - Arabic (Lebanon)', 'ar-LB', 'female', 4],
    ['Microsoft Rami Online (Natural) - Arabic (Lebanon)', 'ar-LB', 'male', 4],
    ['Microsoft Iman Online (Natural) - Arabic (Libya)', 'ar-LY', 'female', 4],
    ['Microsoft Omar Online (Natural) - Arabic (Libya)', 'ar-LY', 'male', 4],
    ['Microsoft Mouna Online (Natural) - Arabic (Morocco)', 'ar-MA', 'female', 4],
    ['Microsoft Jamal Online (Natural) - Arabic (Morocco)', 'ar-MA', 'male', 4],
    ['Microsoft Aysha Online (Natural) - Arabic (Oman)', 'ar-OM', 'female', 4],
    ['Microsoft Abdullah Online (Natural) - Arabic (Oman)', 'ar-OM', 'male', 4],
    ['Microsoft Amal Online (Natural) - Arabic (Qatar)', 'ar-QA', 'female', 4],
    ['Microsoft Moaz Online (Natural) - Arabic (Qatar)', 'ar-QA', 'male', 4],
    ['Microsoft Zariyah Online (Natural) - Arabic (Saudi Arabia)', 'ar-SA', 'female', 4],
    ['Microsoft Hamed Online (Natural) - Arabic (Saudi Arabia)', 'ar-SA', 'male', 4],
    ['Microsoft Amany Online (Natural) - Arabic (Syria)', 'ar-SY', 'female', 4],
    ['Microsoft Laith Online (Natural) - Arabic (Syria)', 'ar-SY', 'male', 4],
    ['Microsoft Reem Online (Natural) - Arabic (Tunisia)', 'ar-TN', 'female', 4],
    ['Microsoft Hedi Online (Natural) - Arabic (Tunisia)', 'ar-TN', 'male', 4],
    ['Microsoft Fatima Online (Natural) - Arabic (United Arab Emirates)', 'ar-AE', 'female', 4],
    ['Microsoft Hamdan Online (Natural) - Arabic (United Arab Emirates)', 'ar-AE', 'male', 4],
    ['Microsoft Maryam Online (Natural) - Arabic (Yemen)', 'ar-YE', 'female', 4],
    ['Microsoft Saleh Online (Natural) - Arabic (Yemen)', 'ar-YE', 'male', 4],
    ['Majed', 'ar-001', 'male', 3],
    ['Microsoft Hoda - Arabic (Arabic )', 'ar-EG', 'female', 2],
    ['Microsoft Naayf - Arabic (Saudi Arabia)', 'ar-AS', 'male', 2],
    ['Android Speech Recognition and Synthesis from Google ar-xa-x-arc-network', 'ar', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google ar-xa-x-arz-network', 'ar', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google ar-xa-x-ard-network', 'ar', 'male', 3],
    ['Android Speech Recognition and Synthesis from Google ar-xa-x-are-network', 'ar', 'male', 3],
];

export default data;
