export default [
    {
        name: 'Microsoft Xiaoxiao Online (Natural) - Chinese (Mainland)',
        lang: 'cmn-CN',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Xiaoyi Online (Natural) - Chinese (Mainland)',
        lang: 'cmn-CN',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Yunxi Online (Natural) - Chinese (Mainland)',
        lang: 'cmn-CN',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Yunxia Online (Natural) - Chinese (Mainland)',
        lang: 'cmn-CN',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Xiaobei Online (Natural) - Chinese (Northeastern Mandarin)',
        lang: 'cmn-CN-liaoning',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Xiaoni Online (Natural) - Chinese (Zhongyuan Mandarin Shaanxi)',
        lang: 'cmn-CN-shaanxi',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Yunjian Online (Natural) - Chinese (Mainland)',
        lang: 'cmn-CN',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Yunyang Online (Natural) - Chinese (Mainland)',
        lang: 'cmn-CN',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft HsiaoChen Online (Natural) - Chinese (Taiwan)',
        lang: 'cmn-TW',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft HsiaoYu Online (Natural) - Chinese (Taiwanese Mandarin)',
        lang: 'cmn-TW',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft YunJhe Online (Natural) - Chinese (Taiwan)',
        lang: 'cmn-TW',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Tingting',
        lang: 'cmn-CN',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Yu-shu',
        lang: 'cmn-CN',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Li-Mu',
        lang: 'cmn-CN',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Haohao',
        lang: 'cmn-CN-shaanxi',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Google 普通话（中国大陆）',
        lang: 'cmn-CN',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google 國語（臺灣）',
        lang: 'cmn-TW',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Microsoft Huihui - Chinese (Simplified, PRC)',
        lang: 'cmn-CN',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Yaoyao - Chinese (Simplified, PRC)',
        lang: 'cmn-CN',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Kangkang - Chinese (Simplified, PRC)',
        lang: 'cmn-CN',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Yating - Chinese (Traditional, Taiwan)',
        lang: 'cmn-TW',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Hanhan - Chinese (Traditional, Taiwan)',
        lang: 'cmn-TW',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Zhiwei - Chinese (Traditional, Taiwan)',
        lang: 'cmn-TW',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google cmn-CN-x-ccc-network',
        lang: 'cmn-CN',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google cmn-CN-x-ssa-network',
        lang: 'cmn-CN',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google cmn-CN-x-ccd-network',
        lang: 'cmn-CN',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google cmn-CN-x-cce-network',
        lang: 'cmn-CN',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google cmn-TW-x-ctc-network',
        lang: 'cmn-TW',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google cmn-TW-x-ctd-network',
        lang: 'cmn-TW',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google cmn-TW-x-cte-network',
        lang: 'cmn-CTW',
        type: 'male',
        quality: 3,
    },
];
