import type { Voice } from '../Voice';

const data: Voice[] = [
    ['Microsoft Xiaoxiao Online (Natural) - Chinese (Mainland)', 'cmn-CN', 'female', 4],
    ['Microsoft Xiaoyi Online (Natural) - Chinese (Mainland)', 'cmn-CN', 'female', 4],
    ['Microsoft Yunxi Online (Natural) - Chinese (Mainland)', 'cmn-CN', 'female', 4],
    ['Microsoft Yunxia Online (Natural) - Chinese (Mainland)', 'cmn-CN', 'female', 4],
    ['Microsoft Xiaobei Online (Natural) - Chinese (Northeastern Mandarin)', 'cmn-CN-liaoning', 'female', 4],
    ['Microsoft Xiaoni Online (Natural) - Chinese (Zhongyuan Mandarin Shaanxi)', 'cmn-CN-shaanxi', 'female', 4],
    ['Microsoft Yunjian Online (Natural) - Chinese (Mainland)', 'cmn-CN', 'male', 4],
    ['Microsoft Yunyang Online (Natural) - Chinese (Mainland)', 'cmn-CN', 'male', 4],
    ['Microsoft HsiaoChen Online (Natural) - Chinese (Taiwan)', 'cmn-TW', 'female', 4],
    ['Microsoft HsiaoYu Online (Natural) - Chinese (Taiwanese Mandarin)', 'cmn-TW', 'female', 4],
    ['Microsoft YunJhe Online (Natural) - Chinese (Taiwan)', 'cmn-TW', 'male', 4],
    ['Tingting', 'cmn-CN', 'female', 2],
    ['Yu-shu', 'cmn-CN', 'female', 2],
    ['Li-Mu', 'cmn-CN', 'male', 2],
    ['Haohao', 'cmn-CN-shaanxi', 'male', 2],
    ['Google 普通话（中国大陆）', 'cmn-CN', 'female', 3],
    ['Google 國語（臺灣）', 'cmn-TW', 'female', 3],
    ['Microsoft Huihui - Chinese (Simplified, PRC)', 'cmn-CN', 'female', 2],
    ['Microsoft Yaoyao - Chinese (Simplified, PRC)', 'cmn-CN', 'female', 2],
    ['Microsoft Kangkang - Chinese (Simplified, PRC)', 'cmn-CN', 'male', 2],
    ['Microsoft Yating - Chinese (Traditional, Taiwan)', 'cmn-TW', 'female', 2],
    ['Microsoft Hanhan - Chinese (Traditional, Taiwan)', 'cmn-TW', 'female', 2],
    ['Microsoft Zhiwei - Chinese (Traditional, Taiwan)', 'cmn-TW', 'male', 2],
    ['Android Speech Recognition and Synthesis from Google cmn-CN-x-ccc-network', 'cmn-CN', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google cmn-CN-x-ssa-network', 'cmn-CN', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google cmn-CN-x-ccd-network', 'cmn-CN', 'male', 3],
    ['Android Speech Recognition and Synthesis from Google cmn-CN-x-cce-network', 'cmn-CN', 'male', 3],
    ['Android Speech Recognition and Synthesis from Google cmn-TW-x-ctc-network', 'cmn-TW', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google cmn-TW-x-ctd-network', 'cmn-TW', 'male', 3],
    ['Android Speech Recognition and Synthesis from Google cmn-TW-x-cte-network', 'cmn-CTW', 'male', 3],
];

export default data;
