export default [
    {
        name: 'Microsoft SeraphinaMultilingual Online (Natural) - German (Germany)',
        lang: 'de-DE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Amala Online (Natural) - German (Germany)',
        lang: 'de-DE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Katja Online (Natural) - German (Germany)',
        lang: 'de-DE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft FlorianMultilingual Online (Natural) - German (Germany)',
        lang: 'de-DE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Conrad Online (Natural) - German (Germany)',
        lang: 'de-DE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Killian Online (Natural) - German (Germany)',
        lang: 'de-DE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Ingrid Online (Natural) - German (Austria)',
        lang: 'de-AT',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Jonas Online (Natural) - German (Austria)',
        lang: 'de-AT',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Leni Online (Natural) - German (Switzerland)',
        lang: 'de-CH',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Jan Online (Natural) - German (Switzerland)',
        lang: 'de-CH',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Anna',
        lang: 'de-DE',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Helena',
        lang: 'de-DE',
        type: 'female',
        quality: 1,
    },
    {
        name: 'Martin',
        lang: 'de-DE',
        type: 'male',
        quality: 1,
    },
    {
        name: 'Weibliche Google-Stimme (Deutschland)',
        lang: 'de-DE',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Microsoft Hedda - German (Germany)',
        lang: 'de-DE',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Katja - German (Germany)',
        lang: 'de-DE',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Stefan - German (Germany)',
        lang: 'de-DE',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Michael - German (Austria)',
        lang: 'de-AT',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Karsten - German (Switzerland)',
        lang: 'de-CH',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Google Deutsch 2 (Natural)',
        lang: 'de-DE',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google Deutsch 1 (Natural)',
        lang: 'de-DE',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google Deutsch 3 (Natural)',
        lang: 'de-DE',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google Deutsch 4 (Natural)',
        lang: 'de-DE',
        type: 'male',
        quality: 3,
    },
];
