import type { Voice } from '../Voice';

const data: Voice[] = [
    ['Microsoft EmmaMultilingual Online (Natural) - English (United States)', 'en-US', 'female', 4],
    ['Microsoft AvaMultilingual Online (Natural) - English (United States)', 'en-US', 'female', 4],
    ['Microsoft Jenny Online (Natural) - English (United States)', 'en-US', 'female', 4],
    ['Microsoft Aria Online (Natural) - English (United States)', 'en-US', 'female', 4],
    ['Microsoft Michelle Online (Natural) - English (United States)', 'en-US', 'female', 4],
    ['Microsoft Ana Online (Natural) - English (United States)', 'en-US', 'female', 4],
    ['Microsoft AndrewMultilingual Online (Natural) - English (United States)', 'en-US', 'male', 4],
    ['Microsoft BrianMultilingual Online (Natural) - English (United States)', 'en-US', 'male', 4],
    ['Microsoft Guy Online (Natural) - English (United States)', 'en-US', 'male', 4],
    ['Microsoft Eric Online (Natural) - English (United States)', 'en-US', 'male', 4],
    ['Microsoft Steffan Online (Natural) - English (United States)', 'en-US', 'male', 4],
    ['Microsoft Christopher Online (Natural) - English (United States)', 'en-US', 'male', 4],
    ['Microsoft Roger Online (Natural) - English (United States)', 'en-US', 'male', 4],
    ['Microsoft Sonia Online (Natural) - English (United Kingdom)', 'en-GB', 'female', 4],
    ['Microsoft Libby Online (Natural) - English (United Kingdom)', 'en-GB', 'female', 4],
    ['Microsoft Maisie Online (Natural) - English (United Kingdom)', 'en-GB', 'female', 4],
    ['Microsoft Ryan Online (Natural) - English (United Kingdom)', 'en-GB', 'male', 4],
    ['Microsoft Thomas Online (Natural) - English (United Kingdom)', 'en-GB', 'male', 4],
    ['Microsoft Natasha Online (Natural) - English (Australia)', 'en-AU', 'female', 4],
    ['Microsoft Hayley Online - English (Australia)', 'en-AU', 'female', 4],
    ['Microsoft William Online (Natural) - English (Australia)', 'en-AU', 'male', 4],
    ['Microsoft Clara Online (Natural) - English (Canada)', 'en-CA', 'female', 4],
    ['Microsoft Heather Online - English (Canada)', 'en-CA', 'female', 4],
    ['Microsoft Liam Online (Natural) - English (Canada)', 'en-CA', 'male', 4],
    ['Microsoft Neerja Online (Natural) - English (India)', 'en-IN', 'female', 4],
    ['Microsoft Prabhat Online (Natural) - English (India)', 'en-IN', 'male', 4],
    ['Microsoft Emily Online (Natural) - English (Ireland)', 'en-IE', 'female', 4],
    ['Microsoft Connor Online (Natural) - English (Ireland)', 'en-IE', 'male', 4],
    ['Microsoft Leah Online (Natural) - English (South Africa)', 'en-ZA', 'female', 4],
    ['Microsoft Luke Online (Natural) - English (South Africa)', 'en-ZA', 'male', 4],
    ['Microsoft Yan Online (Natural) - English (Hong Kong SAR)', 'en-HK', 'female', 4],
    ['Microsoft Sam Online (Natural) - English (Hongkong)', 'en-HK', 'male', 4],
    ['Microsoft Asilia Online (Natural) - English (Kenya)', 'en-KE', 'female', 4],
    ['Microsoft Chilemba Online (Natural) - English (Kenya)', 'en-KE', 'male', 4],
    ['Microsoft Molly Online (Natural) - English (New Zealand)', 'en-NZ', 'female', 4],
    ['Microsoft Mitchell Online (Natural) - English (New Zealand)', 'en-NZ', 'male', 4],
    ['Microsoft Ezinne Online (Natural) - English (Nigeria)', 'en-NG', 'female', 4],
    ['Microsoft Abeo Online (Natural) - English (Nigeria)', 'en-NG', 'male', 4],
    ['Microsoft Rosa Online (Natural) - English (Philippines)', 'en-PH', 'female', 4],
    ['Microsoft James Online (Natural) - English (Philippines)', 'en-PH', 'male', 4],
    ['Microsoft Luna Online (Natural) - English (Singapore)', 'en-SG', 'female', 4],
    ['Microsoft Wayne Online (Natural) - English (Singapore)', 'en-SG', 'male', 4],
    ['Microsoft Imani Online (Natural) - English (Tanzania)', 'en-TZ', 'female', 4],
    ['Microsoft Elimu Online (Natural) - English (Tanzania)', 'en-TZ', 'male', 4],
    ['Nicky', 'en-US', 'female', 2],
    ['Samantha', 'en-US', 'female', 2],
    ['Aaron', 'en-US', 'male', 1],
    ['Martha', 'en-GB', 'female', 1],
    ['Daniel', 'en-GB', 'male', 2],
    ['Arthur', 'en-GB', 'male', 1],
    ['Karen', 'en-AU', 'female', 3],
    ['Catherine', 'en-AU', 'female', 1],
    ['Gordon', 'en-AU', 'male', 1],
    ['Rishi', 'en-IN', 'female', 2],
    ['Google US English', 'en-US', 'female', 3],
    ['Google UK English Female', 'en-GB', 'female', 3],
    ['Google UK English Male', 'en-GB', 'male', 3],
    ['Microsoft Zira - English (United States)', 'en-US', 'female', 2],
    ['Microsoft David - English (United States)', 'en-US', 'male', 2],
    ['Microsoft Mark - English (United States)', 'en-US', 'male', 2],
    ['Microsoft Hazel - English (Great Britain)', 'en-GB', 'female', 2],
    ['Microsoft Susan - English (Great Britain)', 'en-GB', 'female', 2],
    ['Microsoft George - English (Great Britain)', 'en-GB', 'male', 2],
    ['Microsoft Catherine - English (Austalia)', 'en-AU', 'female', 2],
    ['Microsoft Richard - English (Australia)', 'en-AU', 'male', 2],
    ['Microsoft Linda - English (Canada)', 'en-CA', 'female', 2],
    ['Microsoft Richard - English (Canada)', 'en-CA', 'male', 2],
    ['Microsoft Heera - English (India)', 'en-IN', 'female', 2],
    ['Microsoft Ravi - English (India)', 'en-IN', 'male', 2],
    ['Microsoft Sean - English (Ireland)', 'en-IE', 'male', 2],
    ['Google US English 5 (Natural)', 'en-US', 'female', 3],
    ['Google US English 1 (Natural)', 'en-US', 'female', 3],
    ['Google US English 2 (Natural)', 'en-US', 'female', 3],
    ['Google US English 7 (Natural)', 'en-US', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google en-us-x-sfg-network', 'en-US', 'female', 2],
    ['Chrome OS US English 8', 'en-US', 'female', 1],
    ['Google US English 4 (Natural)', 'en-US', 'male', 3],
    ['Google US English 3 (Natural)', 'en-US', 'male', 3],
    ['Google US English 6 (Natural)', 'en-US', 'male', 3],
    ['Google UK English 2 (Natural)', 'en-GB', 'female', 3],
    ['Google UK English 4 (Natural)', 'en-GB', 'female', 3],
    ['Google UK English 6 (Natural)', 'en-GB', 'female', 3],
    ['Chrome OS UK English 7', 'en-GB', 'female', 1],
    ['Google UK English 1 (Natural)', 'en-GB', 'male', 3],
    ['Google UK English 3 (Natural)', 'en-GB', 'male', 3],
    ['Google UK English 5 (Natural)', 'en-GB', 'male', 3],
    ['Google Australian English 1 (Natural)', 'en-AU', 'female', 3],
    ['Google Australian English 3 (Natural)', 'en-AU', 'female', 3],
    ['Google Australian English 2 (Natural)', 'en-AU', 'female', 3],
    ['Google Australian English 4 (Natural)', 'en-AU', 'female', 3],
    ['Chrome OS Australian English 5', 'en-AU', 'male', 3],
    ['Android Speech Recognition and Synthesis from Google en-in-x-ena-network', 'en-IN', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google en-in-x-enc-network', 'en-IN', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google en-in-x-end-network', 'en-IN', 'male', 3],
    ['Android Speech Recognition and Synthesis from Google en-in-x-ene-network', 'en-IN', 'male', 3],
];

export default data;
