import type { Voice } from '../Voice';

const data: Voice[] = [
    {
        name: 'Microsoft EmmaMultilingual Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft AvaMultilingual Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Jenny Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Aria Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Michelle Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Ana Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft AndrewMultilingual Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft BrianMultilingual Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Guy Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Eric Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Steffan Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Christopher Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Roger Online (Natural) - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Sonia Online (Natural) - English (United Kingdom)',
        lang: 'en-GB',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Libby Online (Natural) - English (United Kingdom)',
        lang: 'en-GB',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Maisie Online (Natural) - English (United Kingdom)',
        lang: 'en-GB',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Ryan Online (Natural) - English (United Kingdom)',
        lang: 'en-GB',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Thomas Online (Natural) - English (United Kingdom)',
        lang: 'en-GB',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Natasha Online (Natural) - English (Australia)',
        lang: 'en-AU',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Hayley Online - English (Australia)',
        lang: 'en-AU',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft William Online (Natural) - English (Australia)',
        lang: 'en-AU',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Clara Online (Natural) - English (Canada)',
        lang: 'en-CA',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Heather Online - English (Canada)',
        lang: 'en-CA',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Liam Online (Natural) - English (Canada)',
        lang: 'en-CA',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Neerja Online (Natural) - English (India)',
        lang: 'en-IN',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Prabhat Online (Natural) - English (India)',
        lang: 'en-IN',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Emily Online (Natural) - English (Ireland)',
        lang: 'en-IE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Connor Online (Natural) - English (Ireland)',
        lang: 'en-IE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Leah Online (Natural) - English (South Africa)',
        lang: 'en-ZA',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Luke Online (Natural) - English (South Africa)',
        lang: 'en-ZA',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Yan Online (Natural) - English (Hong Kong SAR)',
        lang: 'en-HK',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Sam Online (Natural) - English (Hongkong)',
        lang: 'en-HK',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Asilia Online (Natural) - English (Kenya)',
        lang: 'en-KE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Chilemba Online (Natural) - English (Kenya)',
        lang: 'en-KE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Molly Online (Natural) - English (New Zealand)',
        lang: 'en-NZ',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Mitchell Online (Natural) - English (New Zealand)',
        lang: 'en-NZ',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Ezinne Online (Natural) - English (Nigeria)',
        lang: 'en-NG',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Abeo Online (Natural) - English (Nigeria)',
        lang: 'en-NG',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Rosa Online (Natural) - English (Philippines)',
        lang: 'en-PH',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft James Online (Natural) - English (Philippines)',
        lang: 'en-PH',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Luna Online (Natural) - English (Singapore)',
        lang: 'en-SG',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Wayne Online (Natural) - English (Singapore)',
        lang: 'en-SG',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Imani Online (Natural) - English (Tanzania)',
        lang: 'en-TZ',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Elimu Online (Natural) - English (Tanzania)',
        lang: 'en-TZ',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Nicky',
        lang: 'en-US',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Samantha',
        lang: 'en-US',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Aaron',
        lang: 'en-US',
        type: 'male',
        quality: 1,
    },
    {
        name: 'Martha',
        lang: 'en-GB',
        type: 'female',
        quality: 1,
    },
    {
        name: 'Daniel',
        lang: 'en-GB',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Arthur',
        lang: 'en-GB',
        type: 'male',
        quality: 1,
    },
    {
        name: 'Karen',
        lang: 'en-AU',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Catherine',
        lang: 'en-AU',
        type: 'female',
        quality: 1,
    },
    {
        name: 'Gordon',
        lang: 'en-AU',
        type: 'male',
        quality: 1,
    },
    {
        name: 'Rishi',
        lang: 'en-IN',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Google US English',
        lang: 'en-US',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google UK English Female',
        lang: 'en-GB',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google UK English Male',
        lang: 'en-GB',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Microsoft Zira - English (United States)',
        lang: 'en-US',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft David - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Mark - English (United States)',
        lang: 'en-US',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Hazel - English (Great Britain)',
        lang: 'en-GB',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Susan - English (Great Britain)',
        lang: 'en-GB',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft George - English (Great Britain)',
        lang: 'en-GB',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Catherine - English (Austalia)',
        lang: 'en-AU',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Richard - English (Australia)',
        lang: 'en-AU',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Linda - English (Canada)',
        lang: 'en-CA',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Richard - English (Canada)',
        lang: 'en-CA',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Heera - English (India)',
        lang: 'en-IN',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Ravi - English (India)',
        lang: 'en-IN',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Sean - English (Ireland)',
        lang: 'en-IE',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Google US English 5 (Natural)',
        lang: 'en-US',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google US English 1 (Natural)',
        lang: 'en-US',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google US English 2 (Natural)',
        lang: 'en-US',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google US English 7 (Natural)',
        lang: 'en-US',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google en-us-x-sfg-network',
        lang: 'en-US',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Chrome OS US English 8',
        lang: 'en-US',
        type: 'female',
        quality: 1,
    },
    {
        name: 'Google US English 4 (Natural)',
        lang: 'en-US',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google US English 3 (Natural)',
        lang: 'en-US',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google US English 6 (Natural)',
        lang: 'en-US',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google UK English 2 (Natural)',
        lang: 'en-GB',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google UK English 4 (Natural)',
        lang: 'en-GB',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google UK English 6 (Natural)',
        lang: 'en-GB',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Chrome OS UK English 7',
        lang: 'en-GB',
        type: 'female',
        quality: 1,
    },
    {
        name: 'Google UK English 1 (Natural)',
        lang: 'en-GB',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google UK English 3 (Natural)',
        lang: 'en-GB',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google UK English 5 (Natural)',
        lang: 'en-GB',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google Australian English 1 (Natural)',
        lang: 'en-AU',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google Australian English 3 (Natural)',
        lang: 'en-AU',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google Australian English 2 (Natural)',
        lang: 'en-AU',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google Australian English 4 (Natural)',
        lang: 'en-AU',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Chrome OS Australian English 5',
        lang: 'en-AU',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google en-in-x-ena-network',
        lang: 'en-IN',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google en-in-x-enc-network',
        lang: 'en-IN',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google en-in-x-end-network',
        lang: 'en-IN',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Android Speech Recognition and Synthesis from Google en-in-x-ene-network',
        lang: 'en-IN',
        type: 'male',
        quality: 3,
    },
];

export default data;
