import type { Voice } from '../Voice';

const data: Voice[] = [
    {
        name: 'Microsoft Elvira Online (Natural) - Spanish (Spain)',
        lang: 'es-ES',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Alvaro Online (Natural) - Spanish (Spain)',
        lang: 'es-ES',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Dalia Online (Natural) - Spanish (Mexico)',
        lang: 'es-MX',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Jorge Online (Natural) - Spanish (Mexico)',
        lang: 'es-MX',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Elena Online (Natural) - Spanish (Argentina)',
        lang: 'es-AR',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Tomas Online (Natural) - Spanish (Argentina)',
        lang: 'es-AR',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Sofia Online (Natural) - Spanish (Bolivia)',
        lang: 'es-BO',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Marcelo Online (Natural) - Spanish (Bolivia)',
        lang: 'es-BO',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Catalina Online (Natural) - Spanish (Chile)',
        lang: 'es-CL',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Lorenzo Online (Natural) - Spanish (Chile)',
        lang: 'es-CL',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Ximena Online (Natural) - Spanish (Colombia)',
        lang: 'es-CO',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Salome Online (Natural) - Spanish (Colombia)',
        lang: 'es-CO',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Gonzalo Online (Natural) - Spanish (Colombia)',
        lang: 'es-CO',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Maria Online (Natural) - Spanish (Costa Rica)',
        lang: 'es-CR',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Juan Online (Natural) - Spanish (Costa Rica)',
        lang: 'es-CR',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Belkys Online (Natural) - Spanish (Cuba)',
        lang: 'es-CU',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Manuel Online (Natural) - Spanish (Cuba)',
        lang: 'es-CU',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Andrea Online (Natural) - Spanish (Ecuador)',
        lang: 'es-EC',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Luis Online (Natural) - Spanish (Ecuador)',
        lang: 'es-EC',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Lorena Online (Natural) - Spanish (El Salvador)',
        lang: 'es-SV',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Rodrigo Online (Natural) - Spanish (El Salvador)',
        lang: 'es-SV',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Paloma Online (Natural) - Spanish (United States)',
        lang: 'es-US',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Alonso Online (Natural) - Spanish (United States)',
        lang: 'es-US',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Marta Online (Natural) - Spanish (Guatemala)',
        lang: 'es-GT',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Andres Online (Natural) - Spanish (Guatemala)',
        lang: 'es-GT',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Teresa Online (Natural) - Spanish (Equatorial Guinea)',
        lang: 'es-GQ',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Javier Online (Natural) - Spanish (Equatorial Guinea)',
        lang: 'es-GQ',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Karla Online (Natural) - Spanish (Honduras)',
        lang: 'es-HN',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Carlos Online (Natural) - Spanish (Honduras)',
        lang: 'es-HN',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Yolanda Online (Natural) - Spanish (Nicaragua)',
        lang: 'es-NI',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Federico Online (Natural) - Spanish (Nicaragua)',
        lang: 'es-NI',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Margarita Online (Natural) - Spanish (Panama)',
        lang: 'es-PA',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Roberto Online (Natural) - Spanish (Panama)',
        lang: 'es-PA',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Tania Online (Natural) - Spanish (Paraguay)',
        lang: 'es-PY',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Mario Online (Natural) - Spanish (Paraguay)',
        lang: 'es-PY',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Camila Online (Natural) - Spanish (Peru)',
        lang: 'es-PE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Alex Online (Natural) - Spanish (Peru)',
        lang: 'es-PE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Karina Online (Natural) - Spanish (Puerto Rico)',
        lang: 'es-PR',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Victor Online (Natural) - Spanish (Puerto Rico)',
        lang: 'es-PR',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Ramona Online (Natural) - Spanish (Dominican Republic)',
        lang: 'es-DO',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Emilio Online (Natural) - Spanish (Dominican Republic)',
        lang: 'es-DO',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Valentina Online (Natural) - Spanish (Uruguay)',
        lang: 'es-UY',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Mateo Online (Natural) - Spanish (Uruguay)',
        lang: 'es-UY',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Microsoft Paola Online (Natural) - Spanish (Venezuela)',
        lang: 'es-VE',
        type: 'female',
        quality: 4,
    },
    {
        name: 'Microsoft Sebastian Online (Natural) - Spanish (Venezuela)',
        lang: 'es-VE',
        type: 'male',
        quality: 4,
    },
    {
        name: 'Mónica',
        lang: 'es-ES',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Paulina',
        lang: 'es-MX',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Google español',
        lang: 'es-ES',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google español de Estados Unidos',
        lang: 'es-US',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Microsoft Helena - Spanish (Spain)',
        lang: 'es-ES',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Laura - Spanish (Spain)',
        lang: 'es-ES',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Pablo - Spanish (Spain)',
        lang: 'es-ES',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Microsoft Sabina - Spanish (Mexico)',
        lang: 'es-MX',
        type: 'female',
        quality: 2,
    },
    {
        name: 'Microsoft Raul - Spanish (Mexico)',
        lang: 'es-MX',
        type: 'male',
        quality: 2,
    },
    {
        name: 'Google español 4 (Natural)',
        lang: 'es-ES',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google español 1 (Natural)',
        lang: 'es-ES',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google español 2 (Natural)',
        lang: 'es-ES',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google español 3 (Natural)',
        lang: 'es-ES',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google español 5 (Natural)',
        lang: 'es-ES',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google español de Estados Unidos 1 (Natural)',
        lang: 'es-US',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google español de Estados Unidos 2 (Natural)',
        lang: 'es-US',
        type: 'female',
        quality: 3,
    },
    {
        name: 'Google español de Estados Unidos 3 (Natural)',
        lang: 'es-US',
        type: 'male',
        quality: 3,
    },
    {
        name: 'Google español de Estados Unidos 4 (Natural)',
        lang: 'es-US',
        type: 'male',
        quality: 3,
    },
];

export default data;
