import type { Voice } from '../Voice';

const data: Voice[] = [
    ['Microsoft Elvira Online (Natural) - Spanish (Spain)', 'es-ES', 'female', 4],
    ['Microsoft Alvaro Online (Natural) - Spanish (Spain)', 'es-ES', 'male', 4],
    ['Microsoft Dalia Online (Natural) - Spanish (Mexico)', 'es-MX', 'female', 4],
    ['Microsoft Jorge Online (Natural) - Spanish (Mexico)', 'es-MX', 'male', 4],
    ['Microsoft Elena Online (Natural) - Spanish (Argentina)', 'es-AR', 'female', 4],
    ['Microsoft Tomas Online (Natural) - Spanish (Argentina)', 'es-AR', 'male', 4],
    ['Microsoft Sofia Online (Natural) - Spanish (Bolivia)', 'es-BO', 'female', 4],
    ['Microsoft Marcelo Online (Natural) - Spanish (Bolivia)', 'es-BO', 'male', 4],
    ['Microsoft Catalina Online (Natural) - Spanish (Chile)', 'es-CL', 'female', 4],
    ['Microsoft Lorenzo Online (Natural) - Spanish (Chile)', 'es-CL', 'male', 4],
    ['Microsoft Ximena Online (Natural) - Spanish (Colombia)', 'es-CO', 'female', 4],
    ['Microsoft Salome Online (Natural) - Spanish (Colombia)', 'es-CO', 'female', 4],
    ['Microsoft Gonzalo Online (Natural) - Spanish (Colombia)', 'es-CO', 'male', 4],
    ['Microsoft Maria Online (Natural) - Spanish (Costa Rica)', 'es-CR', 'female', 4],
    ['Microsoft Juan Online (Natural) - Spanish (Costa Rica)', 'es-CR', 'male', 4],
    ['Microsoft Belkys Online (Natural) - Spanish (Cuba)', 'es-CU', 'female', 4],
    ['Microsoft Manuel Online (Natural) - Spanish (Cuba)', 'es-CU', 'male', 4],
    ['Microsoft Andrea Online (Natural) - Spanish (Ecuador)', 'es-EC', 'female', 4],
    ['Microsoft Luis Online (Natural) - Spanish (Ecuador)', 'es-EC', 'male', 4],
    ['Microsoft Lorena Online (Natural) - Spanish (El Salvador)', 'es-SV', 'female', 4],
    ['Microsoft Rodrigo Online (Natural) - Spanish (El Salvador)', 'es-SV', 'male', 4],
    ['Microsoft Paloma Online (Natural) - Spanish (United States)', 'es-US', 'female', 4],
    ['Microsoft Alonso Online (Natural) - Spanish (United States)', 'es-US', 'male', 4],
    ['Microsoft Marta Online (Natural) - Spanish (Guatemala)', 'es-GT', 'female', 4],
    ['Microsoft Andres Online (Natural) - Spanish (Guatemala)', 'es-GT', 'male', 4],
    ['Microsoft Teresa Online (Natural) - Spanish (Equatorial Guinea)', 'es-GQ', 'female', 4],
    ['Microsoft Javier Online (Natural) - Spanish (Equatorial Guinea)', 'es-GQ', 'male', 4],
    ['Microsoft Karla Online (Natural) - Spanish (Honduras)', 'es-HN', 'female', 4],
    ['Microsoft Carlos Online (Natural) - Spanish (Honduras)', 'es-HN', 'male', 4],
    ['Microsoft Yolanda Online (Natural) - Spanish (Nicaragua)', 'es-NI', 'female', 4],
    ['Microsoft Federico Online (Natural) - Spanish (Nicaragua)', 'es-NI', 'male', 4],
    ['Microsoft Margarita Online (Natural) - Spanish (Panama)', 'es-PA', 'female', 4],
    ['Microsoft Roberto Online (Natural) - Spanish (Panama)', 'es-PA', 'male', 4],
    ['Microsoft Tania Online (Natural) - Spanish (Paraguay)', 'es-PY', 'female', 4],
    ['Microsoft Mario Online (Natural) - Spanish (Paraguay)', 'es-PY', 'male', 4],
    ['Microsoft Camila Online (Natural) - Spanish (Peru)', 'es-PE', 'female', 4],
    ['Microsoft Alex Online (Natural) - Spanish (Peru)', 'es-PE', 'male', 4],
    ['Microsoft Karina Online (Natural) - Spanish (Puerto Rico)', 'es-PR', 'female', 4],
    ['Microsoft Victor Online (Natural) - Spanish (Puerto Rico)', 'es-PR', 'male', 4],
    ['Microsoft Ramona Online (Natural) - Spanish (Dominican Republic)', 'es-DO', 'female', 4],
    ['Microsoft Emilio Online (Natural) - Spanish (Dominican Republic)', 'es-DO', 'male', 4],
    ['Microsoft Valentina Online (Natural) - Spanish (Uruguay)', 'es-UY', 'female', 4],
    ['Microsoft Mateo Online (Natural) - Spanish (Uruguay)', 'es-UY', 'male', 4],
    ['Microsoft Paola Online (Natural) - Spanish (Venezuela)', 'es-VE', 'female', 4],
    ['Microsoft Sebastian Online (Natural) - Spanish (Venezuela)', 'es-VE', 'male', 4],
    ['Mónica', 'es-ES', 'female', 2],
    ['Paulina', 'es-MX', 'female', 2],
    ['Google español', 'es-ES', 'male', 3],
    ['Google español de Estados Unidos', 'es-US', 'female', 3],
    ['Microsoft Helena - Spanish (Spain)', 'es-ES', 'female', 2],
    ['Microsoft Laura - Spanish (Spain)', 'es-ES', 'female', 2],
    ['Microsoft Pablo - Spanish (Spain)', 'es-ES', 'male', 2],
    ['Microsoft Sabina - Spanish (Mexico)', 'es-MX', 'female', 2],
    ['Microsoft Raul - Spanish (Mexico)', 'es-MX', 'male', 2],
    ['Google español 4 (Natural)', 'es-ES', 'female', 3],
    ['Google español 1 (Natural)', 'es-ES', 'female', 3],
    ['Google español 2 (Natural)', 'es-ES', 'female', 3],
    ['Google español 3 (Natural)', 'es-ES', 'male', 3],
    ['Google español 5 (Natural)', 'es-ES', 'male', 3],
    ['Google español de Estados Unidos 1 (Natural)', 'es-US', 'female', 3],
    ['Google español de Estados Unidos 2 (Natural)', 'es-US', 'female', 3],
    ['Google español de Estados Unidos 3 (Natural)', 'es-US', 'male', 3],
    ['Google español de Estados Unidos 4 (Natural)', 'es-US', 'male', 3],
];

export default data;
