import type { Voice } from '../Voice';

const data: Voice[] = [
    ['Microsoft VivienneMultilingual Online (Natural) - French (France)', 'fr-FR', 'female', 4],
    ['Microsoft Denise Online (Natural) - French (France)', 'fr-FR', 'female', 4],
    ['Microsoft Charline Online (Natural) - French (Belgium)', 'fr-BE', 'female', 4],
    ['Microsoft Ariane Online (Natural) - French (Switzerland)', 'fr-CH', 'female', 4],
    ['Microsoft Eloise Online (Natural) - French (France)', 'fr-FR', 'female', 4],
    ['Microsoft RemyMultilingual Online (Natural) - French (France)', 'fr-FR', 'male', 4],
    ['Microsoft Henri Online (Natural) - French (France)', 'fr-FR', 'male', 4],
    ['Microsoft Gerard Online (Natural) - French (Belgium)', 'fr-BE', 'male', 4],
    ['Microsoft Fabrice Online (Natural) - French (Switzerland)', 'fr-CH', 'male', 4],
    ['Microsoft Sylvie Online (Natural) - French (Canada)', 'fr-CA', 'female', 4],
    ['Microsoft Antoine Online (Natural) - French (Canada)', 'fr-CA', 'male', 4],
    ['Microsoft Jean Online (Natural) - French (Canada)', 'fr-CA', 'male', 4],
    ['Microsoft Thierry Online (Natural) - French (Canada)', 'fr-CA', 'male', 4],
    ['Marie', 'fr-FR', 'female', 1],
    ['Thomas', 'fr-FR', 'male', 2],
    ['Amélie', 'fr-CA', 'female', 3],
    ['Google français', 'fr-FR', 'female', 3],
    ['Microsoft Julie - French (France)', 'fr-FR', 'female', 2],
    ['Microsoft Hortence - French (France)', 'fr-FR', 'female', 2],
    ['Microsoft Paul - French (France)', 'fr-FR', 'male', 2],
    ['Microsoft Caroline - French (Canada)', 'fr-CA', 'female', 2],
    ['Microsoft Claude - French (Canada)', 'fr-CA', 'male', 2],
    ['Microsoft Claude - French (Switzerland)', 'fr-CH', 'male', 2],
    ['Google français 4 (Natural)', 'fr-FR', 'female', 3],
    ['Google français 2 (Natural)', 'fr-FR', 'female', 3],
    ['Google français 1 (Natural)', 'fr-FR', 'female', 3],
    ['Google français 5 (Natural)', 'fr-FR', 'male', 3],
    ['Google français 3 (Natural)', 'fr-FR', 'male', 3],
    ['Android Speech Recognition and Synthesis from Google fr-ca-x-caa-network', 'fr-CA', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google fr-ca-x-cac-network', 'fr-CA', 'female', 3],
    ['Android Speech Recognition and Synthesis from Google fr-ca-x-cab-network', 'fr-CA', 'male', 3],
    ['Android Speech Recognition and Synthesis from Google fr-ca-x-cad-network', 'fr-CA', 'male', 3],
];

export default data;
